server: #디폴트 8080
  port: 8080 
  servlet:
    session:
      timeout: 1800 #30분이 기본값
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  address: 127.0.0.1
spring:
  #messages.properties파일 위치 설정.기본값은 messages
  messages:
    basename: i18n/messages #src/main/resources 밑에 i18n폴더 생성후 messages.properties저장
    encoding: UTF-8
  #정적자원의 디폴트 설정
  mvc:
    static-path-pattern: /** 
  web:
    resources:      
      static-location: classpath:/static/ #정적자원의 물리적 위치
      add-mappings: true #자동 매핑 활성화(true:기본값),비 활성화시(false) path-pattern 및 static-location등이 적용되지 않는다
  #데이타 베이스 연결을 위한 설정
  datasource: #필수 설정
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521/XEPDB1
    username: MOG_TEST
    password: MOG_TEST
  #스프링 부트의 디폴트 커넥션 풀인 Hikari 디폴트 설정.
  #https://github.com/brettwooldridge/HikariCP?tab=readme-ov-file#frequently-used
  hikari: #선택 사항(스프링 부트는 hikari가 기본 CP다)
    auto-commit: true     
    connection-timeout: 30000
    maximum-pool-size: 10 
  #Spring Data JPA 설정
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.Oracle12cDialect
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: mogmyowngym@gmail.com
    password: bsbv jxtd keou wxvy
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.smtp.ssl.protocols: TLSv1.2
      
jwttoken:
  secret-key: Nf/vIRqt0/bKThqJ6tOy2M9tqJX+rJxGG9HrZgsBrT4=

